[workspace]
members = ["cyper-core", "cyper"]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/compio-rs/cyper"

[workspace.dependencies]
compio = "0.9.0-beta.3"
cyper-core = { path = "./cyper-core", version = "0.1.0-beta.1" }

cfg-if = "1.0.0"
futures-channel = "0.3.29"
send_wrapper = "0.6"
tokio = "1.33.0"

native-tls = "0.2.11"
rustls = "0.22.0-alpha.4"
rustls-native-certs = "0.7.0-alpha.1"

hyper = "0.14"
