[workspace]
members = ["compio-tls", "compio-http", "compio-http-client"]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Berrysoft <Strawberry_Str@hotmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/compio-rs/compio"

[workspace.dependencies]
compio-buf = "0.2.0-beta.1"
compio-driver = { version = "0.2.0-beta.1", default-features = false }
compio-runtime = "0.2.0-beta.1"
compio-macros = "0.1.1-beta.1"
compio-fs = "0.2.0-beta.1"
compio-io = "0.1.0-beta.1"
compio-net = "0.2.0-beta.1"
compio-signal = "0.1.1-beta.1"
compio-dispatcher = "0.1.0-beta.1"
compio-log = "0.1.0-beta.1"
compio-tls = { path = "./compio-tls", version = "0.1.0" }
compio-http = { path = "./compio-http", version = "0.1.0" }


cfg-if = "1.0.0"
criterion = "0.5.1"
crossbeam-channel = "0.5.8"
crossbeam-queue = "0.3.8"
futures-channel = "0.3.29"
futures-util = "0.3.29"
libc = "0.2.149"
nix = "0.27.1"
once_cell = "1.18.0"
os_pipe = "1.1.4"
paste = "1.0.14"
send_wrapper = "0.6"
slab = "0.4.9"
socket2 = "0.5.5"
tempfile = "3.8.1"
tokio = "1.33.0"
widestring = "1.0.2"
windows-sys = "0.48.0"

native-tls = "0.2.11"
rustls = "0.22.0-alpha.4"
rustls-native-certs = "0.7.0-alpha.1"

hyper = "0.14"
